### ISSUE TITLE
Cannot lift executable

### ISSUE THREAD

**Issue by Thodorissio** [revng/revng#190] opened 2022-06-24 13:25 UTC
I have been trying to lift an executable to llvm IR, but something does not work and i cannot find the documentation for the revng scripts (revng lift/translate/link-for-translation etc).
More specifically I run the following instruction to lift a simple hello executable:
```sh
 ~/orchestra/root/bin/revng lift ~/hello ~/hello_lifted.ll
```
Although the hello_lifted.ll is not the .ll llvm file I have been expecting  (seems more like a .bc llvm file). I converted it to a readable .ll file through the following instruction:
```sh
 llvm-dis ~/hello_lifted.ll -o ~/hello_dis_lifted.ll
```
When I try to recompile the hello_dis_lifted.ll file to an executable:
```sh
clang ~/hello_dis_lifted.ll -o ~/hello_dis_lifted_exec
```
there are many errors that occur due to what i think is an absence of linking:
/home/theodoros/orchestra/root/lib64/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib64/crt1.o(.text+0x20): error: undefined reference to 'main'
/tmp/hello_dis_lifted-fcc9eb.o:null:function rcu_init: error: undefined reference to 'pthread_atfork'
/tmp/hello_dis_lifted-fcc9eb.o:null:function thunk_init: error: undefined reference to 'g_malloc0_n'
/tmp/hello_dis_lifted-fcc9eb.o:null:function uleb128_encode_small: error: undefined reference to 'g_assertion_message_expr'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_init_auxval: error: undefined reference to 'g_malloc'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_init_auxval: error: undefined reference to 'g_realloc'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_mutex_trylock: error: undefined reference to 'pthread_mutex_trylock'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_init: error: undefined reference to 'sem_init'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_destroy: error: undefined reference to 'sem_destroy'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_post: error: undefined reference to 'sem_post'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_timedwait: error: undefined reference to 'sem_trywait'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_timedwait: error: undefined reference to 'sem_timedwait'
/tmp/hello_dis_lifted-fcc9eb.o:null:function qemu_sem_wait: error: undefined reference to 'sem_wait'
...
/tmp/hello_dis_lifted-fcc9eb.o:null:function ignore: error: undefined reference to 'is_executable'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

Should i run something for linking before recompiling?
Is the documentation for the revng scripts availiable somewhere?

Thank you in advance!

**Comment by aleclearmind** [comment] 2022-06-28 15:33
Please try `revng --verbose translate` to see the commands you want to invoke.

**Comment by Thodorissio** [comment] 2022-06-30 11:39
I gave the above instruction a shot but then I faced an Assertion failed error:
![Screenshot from 2022-06-30 14-38-08](https://user-images.githubusercontent.com/71191870/176668418-0eb743d8-fa25-429f-bd4a-0fcd0bd4a460.png)
![Screenshot from 2022-06-30 14-37-47](https://user-images.githubusercontent.com/71191870/176668423-f7b32781-00b7-4159-a2df-212500012184.png)

**Comment by Thodorissio** [comment] 2022-07-03 12:45
So I changed the build a bit and i managed to get the translate script working. The problem is that I do not think that he tranlsate is the proper one for the lifting process (executable -> ll representation)  as it outputs an executable file. I tried the following instruction :
```
~/orchestra/root/bin/revng --verbose lift ~/hello ~/hello.lifted
```
This instruction invokes the instructions i need to follow but an error occurs when I run it:
```
Stack dump:
0.	Program arguments: ../../usr/bin/opt -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngRecompile.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngModel.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngABIAnalyses.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngEarlyFunctionAnalysis.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngTypeShrinking.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngFunctionIsolation.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngBasicAnalyses.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngYield.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngModelImporterBinary.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngABI.so /tmp/tmpa0jq_i1j.ll -o /home/theodoros/hello.lifted -load-binary -binary-path=/home/theodoros/hello -lift -serialize-model 
 #0 0x00007fa6a299d4ff llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x9814ff)
 #1 0x00007fa6a299b7b0 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x97f7b0)
 #2 0x00007fa6a299dac5 (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x981ac5)
 #3 0x00007fa6a66c4420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fa69d5a81be llvm::raw_ostream::operator<<(llvm::StringRef) /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/raw_ostream.h:211:7
 #5 0x00007fa69d5a81be llvm::raw_ostream::operator<<(char const*) /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/raw_ostream.h:221:18
 #6 0x00007fa69d5a81be (anonymous namespace)::CommandLineParser::addOption(llvm::cl::Option*, llvm::cl::SubCommand*) /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:217:31
 #7 0x00007fa69d59d6f5 llvm::StringMapIterBase<llvm::StringMapIterator<llvm::cl::Option*>, llvm::StringMapEntry<llvm::cl::Option*> >::operator++() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:382:11
 #8 0x00007fa69d59d6f5 (anonymous namespace)::CommandLineParser::registerSubCommand(llvm::cl::SubCommand*) /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:378:20
 #9 0x00007fa69d5aa3df void* std::__1::__cxx_atomic_load<void*>(std::__1::__cxx_atomic_base_impl<void*> const*, std::__1::memory_order) /builds/gitlab/revng/orchestra/orchestra/root/lib64/llvm/clang-release/bin/../include/c++/v1/atomic:1006:12
#10 0x00007fa69d5aa3df std::__1::__atomic_base<void*, false>::load(std::__1::memory_order) const /builds/gitlab/revng/orchestra/orchestra/root/lib64/llvm/clang-release/bin/../include/c++/v1/atomic:1615:17
#11 0x00007fa69d5aa3df llvm::ManagedStatic<llvm::cl::SubCommand, llvm::object_creator<llvm::cl::SubCommand>, llvm::object_deleter<llvm::cl::SubCommand> >::operator*() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/ManagedStatic.h:87:21
#12 0x00007fa69d5aa3df (anonymous namespace)::CommandLineParser::CommandLineParser() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:169:25
#13 0x00007fa69d5aa3df llvm::object_creator<(anonymous namespace)::CommandLineParser>::call() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/ManagedStatic.h:23:36
#14 0x00007fa6a2934ec4 llvm::ManagedStaticBase::RegisterManagedStatic(void* (*)(), void (*)(void*)) const (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x918ec4)
#15 0x00007fa69d551994 void* std::__1::__cxx_atomic_load<void*>(std::__1::__cxx_atomic_base_impl<void*> const*, std::__1::memory_order) /builds/gitlab/revng/orchestra/orchestra/root/lib64/llvm/clang-release/bin/../include/c++/v1/atomic:1006:12
#16 0x00007fa69d551994 std::__1::__atomic_base<void*, false>::load(std::__1::memory_order) const /builds/gitlab/revng/orchestra/orchestra/root/lib64/llvm/clang-release/bin/../include/c++/v1/atomic:1615:17
#17 0x00007fa69d551994 llvm::ManagedStatic<(anonymous namespace)::CommandLineParser, llvm::object_creator<(anonymous namespace)::CommandLineParser>, llvm::object_deleter<(anonymous namespace)::CommandLineParser> >::operator*() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/ManagedStatic.h:91:34
#18 0x00007fa69d551994 llvm::ManagedStatic<(anonymous namespace)::CommandLineParser, llvm::object_creator<(anonymous namespace)::CommandLineParser>, llvm::object_deleter<(anonymous namespace)::CommandLineParser> >::operator->() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/ManagedStatic.h:94:29
#19 0x00007fa69d551994 llvm::cl::Option::addArgument() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:445:3
#20 0x00007fa69d551994 llvm::cl::opt<(anonymous namespace)::HelpPrinter, true, llvm::cl::parser<bool> >::done() /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/CommandLine.h:1475:5
#21 0x00007fa69d551994 llvm::cl::opt<(anonymous namespace)::HelpPrinter, true, llvm::cl::parser<bool> >::opt<char [10], llvm::cl::desc, llvm::cl::LocationClass<(anonymous namespace)::HelpPrinter>, llvm::cl::OptionHidden, llvm::cl::ValueExpected, llvm::cl::cat, llvm::cl::sub>(char const (&) [10], llvm::cl::desc const&, llvm::cl::LocationClass<(anonymous namespace)::HelpPrinter> const&, llvm::cl::OptionHidden const&, llvm::cl::ValueExpected const&, llvm::cl::cat const&, llvm::cl::sub const&) /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/include/llvm/Support/CommandLine.h:1499:5
#22 0x00007fa69d551994 __cxx_global_var_init.52 /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:2387:49
#23 0x00007fa69d551994 _GLOBAL__sub_I_CommandLine.cpp /builds/gitlab/revng/orchestra/orchestra/sources/llvm/llvm/lib/Support/CommandLine.cpp:0:0
#24 0x00007fa6a66ffb9a call_init /build/glibc-SzIz7B/glibc-2.31/elf/dl-init.c:71:19
#25 0x00007fa6a66ffca1 _dl_init /build/glibc-SzIz7B/glibc-2.31/elf/dl-init.c:118:9
#26 0x00007fa6a1c3e985 _dl_catch_exception /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:184:18
#27 0x00007fa6a670443d dl_open_worker /build/glibc-SzIz7B/glibc-2.31/elf/dl-open.c:763:5
#28 0x00007fa6a1c3e928 _dl_catch_exception /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:209:18
#29 0x00007fa6a670360a _dl_open /build/glibc-SzIz7B/glibc-2.31/elf/dl-open.c:837:17
#30 0x00007fa6a1a6d34c dlopen_doit /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlopen.c:66:13
#31 0x00007fa6a1c3e928 _dl_catch_exception /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:209:18
#32 0x00007fa6a1c3e9f3 _dl_catch_error /build/glibc-SzIz7B/glibc-2.31/elf/dl-error-skeleton.c:228:12
#33 0x00007fa6a1a6db59 _dlerror_run /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlerror.c:174:40
#34 0x00007fa6a1a6d3da dlopen /build/glibc-SzIz7B/glibc-2.31/dlfcn/dlopen.c:87:51
#35 0x00007fa6a298a9ce llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x96e9ce)
#36 0x00007fa6a293a60e llvm::PluginLoader::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x91e60e)
#37 0x00000000004c3508 (../../usr/bin/opt+0x4c3508)
#38 0x00007fa6a28e350f (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8c750f)
#39 0x00007fa6a28e6687 llvm::cl::ParseCommandLineOptions(int, char const* const*, llvm::StringRef, llvm::raw_ostream*, char const*, bool) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8ca687)
#40 0x00000000004bc8c8 main (../../usr/bin/opt+0x4bc8c8)
#41 0x00007fa6a1b02083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#42 0x00000000004ad0de _start (../../usr/bin/opt+0x4ad0de)
The following command exited with -11:
../../usr/bin/opt -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngRecompile.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngModel.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngABIAnalyses.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngEarlyFunctionAnalysis.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngTypeShrinking.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngFunctionIsolation.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngBasicAnalyses.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngYield.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngModelImporterBinary.so -load /home/theodoros/orchestra/root/lib64/revng/analyses/librevngABI.so /tmp/tmpa0jq_i1j.ll -o /home/theodoros/hello.lifted -load-binary -binary-path=/home/theodoros/hello -lift -serialize-model
```

More specifically the error occurs when i run the following command:
```
/home/theodoros/orchestra/root/bin/revng \
  opt \
  /tmp/tmpa0jq_i1j.ll \
  -o \
  /home/theodoros/hello.lifted \
  -load-binary \
  -binary-path=/home/theodoros/hello \
  -lift
```

**Comment by aleclearmind** [comment] 2022-12-27 09:57
Can you provide the original binary?

**Comment by aleclearmind** [comment] 2023-01-02 13:13
Closing due to lack of information to reproduce the bug. Please feel free to reopen the issue providing the requested information.
Thanks!

**Closed by aleclearmind** 2023-01-02 13:13 UTC
Labels: info-needed
